hub:
   port: 4444
   environments:
       - name:    "Firefox on Windows"
         browser: "*firefox"
       - name:    "Firefox on OS X"
         browser: "*firefox"
       - name:    "Firefox on Linux"
         browser: "*firefox"
       - name:    "IE on Windows"
         browser: "*iehta"
       - name:    "Safari on OS X"
         browser: "*safari"

       - name:    "*firefox"
         browser: "*firefox"
       - name:    "*iexplore"
         browser: "*iexplore"
       - name:    "*iehta"
         browser: "*iehta"
       - name:    "*safari"
         browser: "*safari"
       - name:    "*opera"
         browser: "*opera"
